import { Baloo_Bhai_2, Barrio, Inter } from "next/font/google";
import "./globals.css";

const baloo = Baloo_Bhai_2({
  subsets: ["latin"],
  variable: "--font-baloo",
});

const barrio = Barrio({
  subsets: ["latin"],
  variable: "--font-barrio",
  weight: "400",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${baloo.variable} ${barrio.variable} ${inter.variable} h-full antialiased`}>
      <body className="flex flex-col overflow-x-hidden">
        <div className="">{children}</div>
      </body>
    </html>
  );
}
